/**
 * サイドバーを作成すると、次のことが可能になります。
 - 順序付けられたドキュメントのグループを作成する
 - そのグループの各ドキュメントのサイドバーをレンダリングします
 - 次/前(next/previous)のナビゲーションを提供する

 サイドバーはファイルシステムから生成することも、ここで明示的に定義することもできます。

 サイドバーは必要な数だけ作成できます。
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // デフォルトでは、Docusaurus は docs フォルダー構造からサイドバーを生成します。
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // ただし、サイドバーを手動で作成することもできます
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
